export const TODAY='2026-10-05';
export const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
export const percent=n=>new Intl.NumberFormat('es-CL',{style:'percent',maximumFractionDigits:1}).format(n);
export const roles={Admin:{name:'Camila · Admin',description:'Operación, vehículos y clientes',actions:['acquire','cost','work','document','publish','lead','reserve','sale','financeRequest','postSale','leadStage','opportunity']},CEO:{name:'Tomás · CEO',description:'Estrategia, precios y autorizaciones',actions:['approvePurchase','price']},CFO:{name:'Valentina · CFO',description:'Tesorería, control y cierre financiero',actions:['approveCost','pay','reconcile','dte','commission','financeApprove']}};
export const can=(role,action)=>roles[role]?.actions.includes(action)??false;
export function days(v){return Math.max(0,Math.floor((Date.parse(v.soldAt||TODAY)-Date.parse(v.entered))/86400000));}
export const initialState=()=>({version:1,vehicles:[
 {id:'DEMO-001',brand:'Toyota',model:'RAV4',version:'2.0 CVT Limited',year:2021,km:48200,type:'Propio',stage:'Publicado',buy:15500000,price:18990000,market:18490000,entered:'2026-08-02',parking:3600,capitalRate:.12,commissionRate:.015,prepared:true,docs:true,photo:true,channels:['Chileautos','Mercado Libre'],color:'Gris grafito'},
 {id:'DEMO-002',brand:'Mazda',model:'CX-5',version:'2.0 Touring AT',year:2020,km:61500,type:'Consignado',stage:'Publicado',buy:16150000,price:17000000,market:17500000,entered:'2026-09-14',parking:3000,capitalRate:0,commissionRate:.01,prepared:true,docs:true,photo:true,channels:['Chileautos'],color:'Rojo'},
 {id:'DEMO-003',brand:'Suzuki',model:'Swift',version:'1.2 GLX',year:2022,km:32000,type:'Retoma',stage:'Preparación',buy:7900000,price:10490000,market:10200000,entered:'2026-09-28',parking:2800,capitalRate:.12,commissionRate:.015,prepared:false,docs:false,photo:false,channels:[],color:'Blanco'},
 {id:'DEMO-004',brand:'Kia',model:'Sportage',version:'2.0 EX AT',year:2020,km:70400,type:'Propio',stage:'Reservado',buy:12200000,price:14990000,market:15300000,entered:'2026-09-06',parking:3200,capitalRate:.12,commissionRate:.015,prepared:true,docs:true,photo:true,channels:['Chileautos','Mercado Libre'],color:'Azul'},
 {id:'DEMO-005',brand:'Volkswagen',model:'Golf',version:'1.4 TSI DSG',year:2019,km:78000,type:'Propio',stage:'Vendido',buy:9600000,price:12490000,salePrice:12100000,soldAt:'2026-10-02',market:12300000,entered:'2026-08-20',parking:3000,capitalRate:.12,commissionRate:.015,prepared:true,docs:true,photo:true,channels:[],color:'Plata'},
 {id:'DEMO-006',brand:'Hyundai',model:'Tucson',version:'2.0 GLS AT',year:2021,km:58000,type:'Propio',stage:'Publicado',buy:14000000,price:17690000,market:16890000,entered:'2026-07-21',parking:3500,capitalRate:.12,commissionRate:.015,prepared:true,docs:true,photo:true,channels:['Chileautos','Yapo'],color:'Blanco'},
 {id:'DEMO-007',brand:'Peugeot',model:'2008',version:'1.2 Allure AT',year:2022,km:41000,type:'Propio',stage:'Oportunidad',buy:11200000,price:14990000,market:14600000,entered:TODAY,parking:3000,capitalRate:.12,commissionRate:.015,prepared:false,docs:false,photo:false,channels:[],color:'Naranja',purchaseApproved:false},
 {id:'DEMO-008',brand:'Subaru',model:'Forester',version:'2.0 AWD CVT',year:2020,km:69000,type:'Consignado',stage:'Preparación',buy:16150000,price:17000000,market:17900000,entered:'2026-09-22',parking:3000,capitalRate:0,commissionRate:.01,prepared:false,docs:true,photo:false,channels:[],color:'Verde'}],
 costs:[{id:'C1',vehicle:'DEMO-001',category:'Preparación',vendor:'Taller Norte Demo',amount:420000,status:'Pagado',due:'2026-09-20'},{id:'C2',vehicle:'DEMO-001',category:'Transferencia',vendor:'Gestoría Demo',amount:260000,status:'Pagado',due:'2026-09-20'},{id:'C3',vehicle:'DEMO-002',category:'Detail',vendor:'Estudio Brillo Demo',amount:150000,status:'Aprobado',due:'2026-10-08'},{id:'C4',vehicle:'DEMO-003',category:'Frenos',vendor:'Taller Norte Demo',amount:280000,status:'Pendiente',due:'2026-10-06'},{id:'C5',vehicle:'DEMO-004',category:'Preparación',vendor:'Taller Norte Demo',amount:310000,status:'Pagado',due:'2026-09-20'},{id:'C6',vehicle:'DEMO-005',category:'Preparación',vendor:'Taller Norte Demo',amount:380000,status:'Pagado',due:'2026-09-20'},{id:'C7',vehicle:'DEMO-006',category:'Mecánica',vendor:'Taller Norte Demo',amount:690000,status:'Pagado',due:'2026-09-20'},{id:'C8',vehicle:'DEMO-008',category:'Neumáticos',vendor:'Neumáticos Sur Demo',amount:360000,status:'Pendiente',due:'2026-10-10'}],
 works:[{id:'OT-101',vehicle:'DEMO-003',task:'Frenos y revisión de seguridad',vendor:'Taller Norte Demo',status:'En curso',cost:'C4'},{id:'OT-102',vehicle:'DEMO-008',task:'Cambio de neumáticos',vendor:'Neumáticos Sur Demo',status:'Pendiente',cost:'C8'}],
 leads:[{id:'L1',name:'Cliente Demo A',vehicle:'DEMO-001',channel:'Chileautos',stage:'Visita',next:'Visita · 06 oct, 11:00'},{id:'L2',name:'Cliente Demo B',vehicle:'DEMO-002',channel:'WhatsApp',stage:'Nuevo',next:'Primer contacto hoy'},{id:'L3',name:'Cliente Demo C',vehicle:'DEMO-004',channel:'Mercado Libre',stage:'Reserva',next:'Completar pago y firma'},{id:'L4',name:'Cliente Demo D',vehicle:'DEMO-006',channel:'Meta',stage:'Contactado',next:'Enviar ficha hoy'}],
 reservations:[{id:'R1',vehicle:'DEMO-004',lead:'L3',amount:300000,price:14990000,expires:'2026-10-08',status:'Activa'}],
 financing:[{id:'F1',vehicle:'DEMO-004',amount:10000000,status:'Pendiente',provider:'Financiera Demo',term:36,monthlyRate:.015}],
 receivables:[{id:'AR1',vehicle:'DEMO-005',description:'Saldo venta Golf · Cliente Demo E',amount:12100000,paid:12100000},{id:'AR2',vehicle:'DEMO-004',description:'Anticipo Sportage · Cliente Demo C',amount:300000,paid:0}],
 bank:[{id:'B1',date:'2026-10-02',description:'Abono venta Golf',amount:12100000,reference:'AR1',matched:'AR1'},{id:'B2',date:TODAY,description:'Reserva Sportage',amount:300000,reference:'AR2',matched:null},{id:'B3',date:TODAY,description:'Cargo por identificar',amount:-45990,reference:null,matched:null}],
 recurring:[{id:'G1',name:'Arriendo oficina',vendor:'Inmobiliaria Demo',amount:650000,allocated:false},{id:'G2',name:'Estacionamientos · 8 plazas',vendor:'Parking Demo',amount:720000,allocated:true},{id:'G3',name:'Contabilidad',vendor:'Estudio Contable Demo',amount:180000,allocated:false},{id:'G4',name:'Internet y servicios',vendor:'Servicios Demo',amount:65000,allocated:false},{id:'G5',name:'Portales y publicidad',vendor:'Marketing Demo',amount:240000,allocated:false}],
 documents:[],commissions:[],postSales:[],audit:[{id:'A0',at:'2026-10-05T09:00:00-03:00',actor:'Sistema',action:'Inicio de escenario ficticio',detail:'Datos demo · sin conexiones externas'}]});
export function economics(v,s){const direct=s.costs.filter(c=>c.vehicle===v.id&&!c.settlement).reduce((a,c)=>a+c.amount,0);const holding=days(v)*v.parking;const capital=Math.round((v.type==='Consignado'?0:v.buy)*v.capitalRate*days(v)/365);const price=v.salePrice??v.price;const commission=Math.round(price*v.commissionRate);const gross=price-v.buy-direct;const net=gross-holding-capital-commission;return{direct,holding,capital,commission,gross,net,price,cost:v.buy+direct,returnOnCost:v.buy+direct?gross/(v.buy+direct):null,margin:price?net/price:0,agencyRevenue:price-v.buy,daily:v.parking+Math.round((v.type==='Consignado'?0:v.buy)*v.capitalRate/365)};}
export function recommendation(v,s){const e=economics(v,s);if(v.stage==='Vendido')return'Cierre completado';if(v.stage==='Oportunidad')return e.net/v.price>=.1?'Evaluar compra':'Negociar toma';if(e.net<0)return'Revisar margen';if(days(v)>60&&v.price>v.market)return'Ajustar precio';return'Mantener estrategia';}
const requireThat=(ok,msg)=>{if(!ok)throw new Error(msg);};
const positive=x=>Number.isFinite(Number(x))&&Number(x)>0;
export function transition(s,role,action,p={}){
 requireThat(can(role,action),'Tu perfil no puede realizar esta acción.');const n=structuredClone(s),v=n.vehicles.find(x=>x.id===p.vehicle),id=prefix=>prefix+'-'+(n.audit.length+1);const active=()=>requireThat(v&&v.stage!=='Vendido','Vehículo no disponible.');
 if(action==='opportunity'){requireThat(p.brand?.trim()&&p.model?.trim()&&positive(p.buy)&&positive(p.price),'Completa marca, modelo y precios positivos.');requireThat(['Propio','Consignado','Retoma'].includes(p.type),'Modalidad inválida.');n.vehicles.push({id:id('DEMO'),brand:p.brand.trim(),model:p.model.trim(),version:'Versión demo',year:2021,km:50000,type:p.type,stage:'Oportunidad',buy:Number(p.buy),price:Number(p.price),market:Number(p.price),entered:TODAY,parking:3000,capitalRate:p.type==='Consignado'?0:.12,commissionRate:.015,prepared:false,docs:false,photo:false,channels:[],color:'Por definir',purchaseApproved:false});}
 if(action==='leadStage'){const l=n.leads.find(x=>x.id===p.id);requireThat(l&&['Nuevo','Contactado'].includes(l.stage),'Etapa no modificable.');l.stage=l.stage==='Nuevo'?'Contactado':'Visita';l.next=l.stage==='Visita'?'Coordinar visita demo':'Agendar visita';}
 if(action==='approvePurchase'){requireThat(v?.stage==='Oportunidad','No es una oportunidad.');v.purchaseApproved=true;}
 if(action==='acquire'){requireThat(v?.stage==='Oportunidad'&&v.purchaseApproved,'Requiere aprobación del CEO.');v.stage='Preparación';v.entered=TODAY;if(v.type!=='Consignado')n.costs.push({id:id('ADQ'),vehicle:v.id,category:'Adquisición de vehículo',vendor:'Vendedor Demo',amount:v.buy,status:'Pendiente',due:'2026-10-08',settlement:true});}
 if(action==='cost'){active();requireThat(positive(p.amount)&&p.category?.trim()&&p.vendor?.trim(),'Completa concepto, proveedor y un monto positivo.');n.costs.push({id:id('C'),vehicle:v.id,category:p.category.trim(),vendor:p.vendor.trim(),amount:Number(p.amount),status:'Pendiente',due:'2026-10-12'});}
 if(action==='approveCost'){const c=n.costs.find(x=>x.id===p.id);requireThat(c?.status==='Pendiente','Gasto ya procesado.');c.status='Aprobado';}
 if(action==='pay'){const c=n.costs.find(x=>x.id===p.id);requireThat(c?.status==='Aprobado','El pago requiere aprobación del CFO.');c.status='Pago registrado';n.bank.push({id:id('B'),date:TODAY,description:'Pago demo · '+c.vendor,amount:-c.amount,reference:c.id,matched:null});}
 if(action==='work'){const w=n.works.find(x=>x.id===p.id);requireThat(w&&w.status!=='Completada','Orden ya completada.');w.status='Completada';const car=n.vehicles.find(x=>x.id===w.vehicle);car.prepared=!n.works.some(x=>x.vehicle===car.id&&x.status!=='Completada');}
 if(action==='document'){active();requireThat(['docs','photo','prepared'].includes(p.field),'Documento desconocido.');if(p.field==='prepared')requireThat(!n.works.some(x=>x.vehicle===v.id&&x.status!=='Completada'),'Completa las órdenes de trabajo primero.');v[p.field]=true;}
 if(action==='publish'){active();requireThat(['Preparación','Publicado'].includes(v.stage)&&v.docs&&v.photo&&v.prepared,'Completa documentación, preparación y fotos antes de publicar.');v.channels=['Chileautos','Mercado Libre','Yapo'];v.stage='Publicado';}
 if(action==='price'){active();requireThat(positive(p.amount),'Ingresa un precio positivo.');requireThat(v.stage!=='Reservado','El precio de una reserva está bloqueado.');v.price=Math.round(Number(p.amount));}
 if(action==='lead'){requireThat(p.name?.trim()&&v&&v.stage!=='Vendido','Completa cliente y vehículo disponible.');n.leads.push({id:id('L'),name:p.name.trim(),vehicle:v.id,channel:p.channel||'WhatsApp',stage:'Nuevo',next:'Contactar hoy'});}
 if(action==='reserve'){active();const l=n.leads.find(x=>x.id===p.lead);requireThat(v.stage==='Publicado'&&l?.vehicle===v.id,'Selecciona un lead del vehículo publicado.');requireThat(!n.reservations.some(r=>r.vehicle===v.id&&r.status==='Activa'),'Ya tiene una reserva.');v.stage='Reservado';l.stage='Reserva';n.reservations.push({id:id('R'),vehicle:v.id,lead:l.id,amount:300000,price:v.price,expires:'2026-10-08',status:'Activa'});const rid=id('AR');n.receivables.push({id:rid,vehicle:v.id,description:'Anticipo · '+l.name,amount:300000,paid:0});n.bank.push({id:id('B'),date:TODAY,description:'Anticipo simulado · '+l.name,amount:300000,reference:rid,matched:null});}
 if(action==='financeRequest'){requireThat(v?.stage==='Reservado','Primero reserva el vehículo.');requireThat(!n.financing.some(f=>f.vehicle===v.id),'Ya existe solicitud.');requireThat(positive(p.amount)&&Number(p.amount)<v.price,'Monto de financiamiento inválido.');n.financing.push({id:id('F'),vehicle:v.id,amount:Number(p.amount),status:'Pendiente',provider:'Financiera Demo',term:36,monthlyRate:.015});}
 if(action==='financeApprove'){const f=n.financing.find(x=>x.id===p.id);requireThat(f?.status==='Pendiente','Solicitud ya procesada.');f.status='Aprobado demo';}
 if(action==='sale'){requireThat(v?.stage==='Reservado'&&v.docs,'Reserva y documentación requeridas.');requireThat(!n.financing.some(f=>f.vehicle===v.id&&f.status==='Pendiente'),'CFO debe revisar el financiamiento.');requireThat(!n.receivables.some(r=>r.vehicle===v.id&&r.paid<r.amount),'Concilia el anticipo antes de vender.');const r=n.reservations.find(r=>r.vehicle===v.id&&r.status==='Activa');requireThat(r&&r.expires>=TODAY,'Reserva vencida o ausente.');v.stage='Vendido';v.salePrice=r.price;v.soldAt=TODAY;v.channels=[];r.status='Convertida';n.leads.find(x=>x.id===r.lead).stage='Ganado';const paid=n.receivables.filter(x=>x.vehicle===v.id).reduce((a,x)=>a+x.paid,0),rid=id('AR');n.receivables.push({id:rid,vehicle:v.id,description:'Saldo venta · '+v.model,amount:v.salePrice-paid,paid:0});n.bank.push({id:id('B'),date:TODAY,description:'Saldo venta simulado · '+v.model,amount:v.salePrice-paid,reference:rid,matched:null});if(v.type==='Consignado')n.costs.push({id:id('LIQ'),vehicle:v.id,category:'Liquidación consignante',vendor:'Consignante Demo',amount:v.buy,status:'Pendiente',due:'2026-10-08',settlement:true});}
 if(action==='reconcile'){const b=n.bank.find(x=>x.id===p.id);requireThat(b&&!b.matched&&b.reference,'Movimiento sin correspondencia o ya conciliado.');const r=n.receivables.find(x=>x.id===b.reference),c=n.costs.find(x=>x.id===b.reference);requireThat((r&&b.amount===r.amount-r.paid)||(c&&-b.amount===c.amount&&c.status==='Pago registrado'),'Monto o estado no coincide.');b.matched=b.reference;if(r)r.paid+=b.amount;if(c)c.status='Pagado';}
 if(action==='dte'){requireThat(v?.stage==='Vendido','Requiere una venta.');requireThat(!n.documents.some(x=>x.vehicle===v.id),'Borrador ya generado.');n.documents.push({id:id('DTE-DEMO'),vehicle:v.id,amount:v.salePrice??v.price,status:'Borrador · sin validez tributaria',tax:'Pendiente de clasificación por contador'});}
 if(action==='commission'){requireThat(v?.stage==='Vendido'&&!n.receivables.some(r=>r.vehicle===v.id&&r.paid<r.amount),'Comisión liberable sólo con venta cobrada.');requireThat(!n.commissions.some(c=>c.vehicle===v.id),'Comisión ya liberada.');n.commissions.push({id:id('COM'),vehicle:v.id,amount:economics(v,n).commission,status:'Liquidada demo'});}
 if(action==='postSale'){requireThat(v?.stage==='Vendido'&&p.note?.trim(),'Indica el motivo para un vehículo vendido.');n.postSales.push({id:id('PV'),vehicle:v.id,note:p.note,status:'Abierto'});}
 n.audit.unshift({id:id('AUD'),at:new Date().toISOString(),actor:role,action,detail:JSON.stringify(p)});return n;
}
